### ISSUE TITLE
Enable students to view grades

### ISSUE THREAD

**Issue by esnowgol** [esnowgol/myRepo#1]
**User Story**
As a student, I want to know how well I'm doing in class.

**Tasks**
- [x] Add UI to display grades
- [x] Create Model for Grades
- [x] Create API end points for retrieving grades

**Acceptance Criteria**
Works on Chrome, Firefox, and Edge. Displays the student's grades, and not another student's grades. Student cannot edit grades.

**Acceptance Tests**
1. A student is able to view their grades. 
2. Cannot access other student's grades
3. Students cannot edit grades.
